--- #YAML:1.0
name: Data-Dumper-EasyOO
version: 0.0401
author:
  - Jim Cromie <jcromie@cpan.org>
abstract: wraps DD for easy use of printing styles
license: perl
generated_by: Module::Build version 0.26, without YAML.pm
