---
name: Data-Dumper-EasyOO
version: 0.04_03
author:
  - Jim Cromie <jcromie@cpan.org>
abstract: wraps DD for easy use of various printing styles
license: perl
requires:
  Data::Dumper: 2.00
  perl: 5.005_03
provides:
  Data::Dumper::EasyOO:
    file: lib/Data/Dumper/EasyOO.pm
    version: 0.04_03
generated_by: Module::Build version 0.2608
